version: 2.1
orbs:
  terraform: circleci/terraform@3.2.0
  jinja: jtreutel/jinja@1.1.0
  aws-cli: circleci/aws-cli@3.1.3
  semver: cci-labs/semver@0.0.3

parameters:
  tf-version:
    type: string
    default: "1.8.2"
  oidc_test_role_arn:
    type: string
    default: "arn:aws:iam::992382483259:role/cera-fe-pipeline-role"
  
jobs:
  setup-oidc-and-test-files:
    parameters:
      aws_profile: 
        type: env_var_name
        default: J2_AWS_PROFILE
      oidc_test_role_arn: 
        type: env_var_name
        default: OIDC_TEST_ROLE_ARN
    executor: jinja/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          profile-name: << parameters.aws_profile >>
          role-arn: << pipeline.parameters.oidc_test_role_arn >>
          role-session-name: "cci-ceratf-module-eks-<< pipeline.number >>"
          session-duration: "3600"
      - jinja/render:
          path: .test/
          outputdir: ./
      - persist_to_workspace:
          root: .
          paths:
            - .

  tf-validate:
    docker:
      - image: hashicorp/terraform:<< pipeline.parameters.tf-version >>
    steps:
      - attach_workspace:
          at: .
      - terraform/fmt
      - terraform/validate

workflows:
  version: 2
  main:
    jobs:
      - setup-oidc-and-test-files:
          name: Set up OIDC Auth with AWS & Render Templated Test Files
          context: 
            - se-eks-tf-module-testing
      - tf-validate:
          name: Validate Terraform Plan
          requires: 
            - Set up OIDC Auth with AWS & Render Templated Test Files
      - semver/bump:
          pre-steps: 
            - semver/getfromgit
          post-steps: 
            - run: 
                name: Use new version values
                command: |
                  echo "Tagging as: ${MAJOR}.${MINOR}.${PATCH}"
                  git tag ${MAJOR}.${MINOR}.${PATCH}
                  git push --tags
          requires: [Validate Terraform Plan]

# VS Code Extension Version: 1.4.0
